---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressrouters.homelab.valdron.ca
spec:
  group: homelab.valdron.ca
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                ipAddress:
                  type: string
                ingressClass:
                  type: string
              required:
                - ipAddress
              type: object
          type: object
  names:
    singular: ingressrouter
    plural: ingressrouters
    kind: IngressRouter
    shortNames:
      - ir