---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-operator
spec:
  template:
    spec:
      serviceAccountName: homelab-operator
      containers:
        - name: homelab-operator
          image: jvaldron/homelab-operator
          imagePullPolicy: Always