---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homelab-operator

commonLabels:
  app: homelab-operator

resources:
  - crds/
  - deployment.yaml
  - rbac.yaml
  - service-account.yaml
