---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homelab-operator
rules:
  - apiGroups: ['']
    resources:
      - services
    verbs:
      - get
      - watch
      - list

  - apiGroups: ['networking.k8s.io']
    resources:
      - ingresses
    verbs:
      - get
      - watch
      - list

  - apiGroups: ['apiextensions.k8s.io']
    resources:
      - customresourcedefinitions
    verbs:
      - create

  - apiGroups: ['homelab.valdron.ca']
    resources:
      - devices
      - ingressrouters
      - networks
    verbs:
      - get
      - watch
      - list

  - apiGroups: ['dnsmasq.kvaps.cf']
    resources:
      - dhcphosts
      - dhcpoptions
      - dnshosts
    verbs:
      - create
      - get
      - update

  - apiGroups: ['freeradius.valdron.ca']
    resources:
      - devices
    verbs:
      - create
      - get
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homelab-operator
subjects:
  - kind: ServiceAccount
    name: homelab-operator
    namespace: homelab-operator
roleRef:
  kind: ClusterRole
  name: homelab-operator
  apiGroup: rbac.authorization.k8s.io