---
name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: jvaldron/freeradius-operator

    steps:
      - uses: actions/checkout@v1

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF##*/})
        
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ${REGISTRY}:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push ${REGISTRY}:${{steps.vars.outputs.tag}}
      
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag ${REGISTRY}:latest
      - name: Push the latest Docker image
        run: docker push ${REGISTRY}:latest
